AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: false
  
Metrics/ClassLength:
  Max: 120
  
Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/ClassAndModuleChildren:
  Description: >-
                 Compact style ensures that the parent classes and modules are not reopened for each child class and
                 module.  Reopening the parent class or module can lead to the parent class or module not being loaded
                 as the child already defined it.
  EnforcedStyle: compact
Style/GuardClause:
  Description: >-
                 Modifiers prevent placing break points on just the condition or just the body.  Similarly, coverage of
                 the line cannot tell you if the body is ever executed.
  Enabled: false
Style/IfUnlessModifier:
  Description: >-
                 Modifiers prevent placing break points on just the condition or just the body.  Similarly, coverage of
                 the line cannot tell you if the body is ever executed.
  Enabled: false
Style/StringLiterals:
  Description: >-
                 Double quotes work for Strings in both Ruby and Elixir, so developers switch languages can use
                 consistent quoting. (Single quotes are char lists in Elixir.)
  EnforcedStyle: double_quotes
Style/WhileUntilModifier:
  Description: >-
                 Modifiers prevent placing break points on just the condition or just the body.  Similarly, coverage of
                 the line cannot tell you if the body is ever executed.
  Enabled: false
